language: ruby
jdk: oraclejdk7
notifications:
  email:
    - levi@leviwilson.com
    - jeff.morgan@leandog.com
script:
  - rake release_apk
  - ant test
  - bundle install
  - bundle exec rake spec
install: ant prepare-travis-ci
