language: ruby
jdk: oraclejdk7
notifications:
  email:
    - levi@leviwilson.com
    - jeff.morgan@leandog.com
script:
  - ant test
  - bundle install
  - bundle exec rake spec
install:
  - sudo apt-get install ia32-libs-multiarch
  - sudo apt-get install ia32-libs
  - ant prepare-travis-ci -q
